name: Deploy Prod

on:
  push:
    branches:
      - main

jobs:
  deploy-prod:
    name: Deploy Prod
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.environment }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Build Next.js app
        run: npm run build

      - name: Install AWS Amplify CLI
        run: npm install -g @aws-amplify/cli

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ap-southeast-1

      - name: Amplify CLI Login
        run: amplify pull --appId ${{ secrets.AWS_AMPLIFY_APP_ID }} --envName prod --yes

      - name: Deploy to AWS Amplify
        run: amplify publish --yes
